#dockerImage: "nexus.services.mnscorp.net:6666/mtp-channelorder-esstub-develop:pr-8"
#dockerTag: 0.01
dockerPort: 8080

replicas: 1
replicasMax: 2
cpuTargetPercentage: 50
ingress:
  name: search-assembler-service
  # This will need to be set at deploy time as it differs from environment to environment
  domain: "prod.platform.mnscorp.net"
  subdomain: platform
  # This will enable custom metrics for your application
  metric: true

  # Mark ssl as true to enable SSL on this service
  ssl: true
  access_policy: 'public'
# Change below value if you want to deploy the application in a different namespace
namespace: blomreachmigration-apidevelopment-prod
# Cluster to which application needs to be deployed
cluster: prod
# Pod Resource Values
resources:
  requests:
    memory: 100Mi
    cpu: 200m
environment: prod
